application:
  jwt:
    secretKey: securetextisverylongsecuretextisverylongsecuretextisverylongsecuretextisverylong
    tokenPrefix: 'Bearer '
    tokenExpirationAfterDays: 14
app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/skillsdb
    username: postgres
    password: password
    pool-size: 30